stages:
    - setup
    - test
setup:
    stage: setup
    tags:
        - osx
    script:
        - gem install lolcat
test:
    stage: test
    tags:
        - osx
    script:
        - ./quick-start
