#!/bin/bash
mkdir -p  files
rm files/* -f
echo "start..."
echo "Welcome to mongo-to-amazon-dynamo-db-replication!"| lolcat -F 0.3
echo "  __    __ _____ _____ ___   _____" | lolcat -F 0.3
echo " |   \/   |     |   | |  _|_|     | contact me: mosgreyday@gmail.com" | lolcat -F 0.3
echo " |  |\/|  |  |  | | | |   | |  |  | Copyright Igor Roshchin" | lolcat -F 0.3
echo " |__|  |__|_____|_|___|_____|_____| mongo agent downloads all files " | lolcat -F 0.3
echo "                                    from provided db.coll of mongoDB" | lolcat -F 0.3
echo ""
cd include
g++ -std=c++1z -o count count-mongo-files-in-collection.cpp $(pkg-config --cflags --libs libmongoc-1.0)
files_in_collection="$(./count)"
cd ..
echo "I ve counted ${files_in_collection} files in collection ..." | lolcat -F 0.3
echo "Im starting downloading files..." | lolcat -F 0.3
./mongo --path=/home/y/Documents/m-ad/files/
count_downloaded="$(find files/ -iname "*" | wc -l)"
count_downloaded=$((count_downloaded - 1))
echo "I ve downloaded ${count_downloaded}" | lolcat -F 0.3
count_delta=$((files_in_collection - count_downloaded ))
echo "${files_in_collection} files found, ${count_downloaded} files downloaded, ${count_delta} files lost in the deeps of internet" | lolcat -F 0.3
echo "start ended..."
